---
- name: "Gather Juniper Device Facts"
  hosts: switches
  gather_facts: no

  tasks:
    - name: "TASK 1: Get facts"
      juniper.device.facts:
        host: "{{ ansible_host }}"
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"

      register: response

    - name: "TASK 2: Print Device Summary"
      debug:
        msg:
          - "Hostname: {{ response.facts.hostname }}"
          - "Model: {{ response.facts.model }}"
          - "Version: {{ response.facts.version }}"
          - "Serial: {{ response.facts.serialnumber }}"