---
- name: "Play 1: Gather and Print Device Facts"
  hosts: juniper_switches
  gather_facts: no
  connection: local

  tasks:
    - name: "TASK 1: Get Juniper Device Facts"       
      juniper.device.facts:
        user: "{{ ansible_user }}"
        passwd: "{{ ansible_password }}"
      register: response

    - name: "TASK 2: Print Device Summary"
      debug:
        msg:
          - "Hostname: {{ response.facts.hostname }}"
          - "Model: {{ response.facts.model }}"
          - "Version: {{ response.facts.version }}"
          - "Serial: {{ response.facts.serialnumber }}"